from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..types import UNSET, Unset
from typing import cast
import datetime

if TYPE_CHECKING:
    from ..models.order_ledgers_item import OrderLedgersItem
    from ..models.order_package import OrderPackage


T = TypeVar("T", bound="Order")


@_attrs_define
class Order:
    is_auto_renewal: bool
    package: OrderPackage
    data_remaining: int
    ledgers: list[OrderLedgersItem]
    data_updated: datetime.datetime
    updated: datetime.datetime
    created: datetime.datetime
    id: str | Unset = UNSET
    auto_renewal_percentage: int | Unset = UNSET
    """ When this percentage of the data allowance has been consumed, the order is automatically renewed if the user
    has sufficient balance. Set to 0 to disable auto-renewal. 80 → renew when 80% of data is used """
    auto_renewal_data: int | Unset = UNSET
    """ Amount of data in GB to add when auto-renewal is triggered. Set to 0 to use the package default. """
    proxy_password: str | Unset = UNSET
    """ Password used by the customer to authenticate proxy connections. Auto-generated by default — change only if
    a custom value is needed. Must be between 4 and 64 characters. """
    proxy_password_reset: datetime.datetime | None | Unset = UNSET
    """ Timestamp of the last proxy password change. Read-only — updated automatically whenever the password is
    rotated. """
    pools: list[str] | Unset = UNSET
    """ Private proxy pools assigned to this order. Pools restrict which proxy IPs are available to this customer.
    Leave blank to use the full provider pool. """
    data: int | Unset = UNSET
    """ Total data allowance for this order in bytes. 1073741824 = 1 GiB 10737418240 = 10 GiB """
    data_spent: int | Unset = UNSET
    """ Total bytes consumed from this order's data allowance so far. Updated in real time as the customer uses the
    proxy. """
    latest_data_top_up: int | Unset = UNSET
    """ Amount of data added to this order in bytes during the most recent top-up. """
    latest_data_top_up_date: datetime.datetime | None | Unset = UNSET
    """ Timestamp of the most recent data top-up, set when an invoice is fulfilled. """
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.order_ledgers_item import OrderLedgersItem
        from ..models.order_package import OrderPackage

        is_auto_renewal = self.is_auto_renewal

        package = self.package.to_dict()

        data_remaining = self.data_remaining

        ledgers = []
        for ledgers_item_data in self.ledgers:
            ledgers_item = ledgers_item_data.to_dict()
            ledgers.append(ledgers_item)

        data_updated = self.data_updated.isoformat()

        updated = self.updated.isoformat()

        created = self.created.isoformat()

        id = self.id

        auto_renewal_percentage = self.auto_renewal_percentage

        auto_renewal_data = self.auto_renewal_data

        proxy_password = self.proxy_password

        proxy_password_reset: None | str | Unset
        if isinstance(self.proxy_password_reset, Unset):
            proxy_password_reset = UNSET
        elif isinstance(self.proxy_password_reset, datetime.datetime):
            proxy_password_reset = self.proxy_password_reset.isoformat()
        else:
            proxy_password_reset = self.proxy_password_reset

        pools: list[str] | Unset = UNSET
        if not isinstance(self.pools, Unset):
            pools = self.pools

        data = self.data

        data_spent = self.data_spent

        latest_data_top_up = self.latest_data_top_up

        latest_data_top_up_date: None | str | Unset
        if isinstance(self.latest_data_top_up_date, Unset):
            latest_data_top_up_date = UNSET
        elif isinstance(self.latest_data_top_up_date, datetime.datetime):
            latest_data_top_up_date = self.latest_data_top_up_date.isoformat()
        else:
            latest_data_top_up_date = self.latest_data_top_up_date

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "is_auto_renewal": is_auto_renewal,
                "package": package,
                "data_remaining": data_remaining,
                "ledgers": ledgers,
                "data_updated": data_updated,
                "updated": updated,
                "created": created,
            }
        )
        if id is not UNSET:
            field_dict["id"] = id
        if auto_renewal_percentage is not UNSET:
            field_dict["auto_renewal_percentage"] = auto_renewal_percentage
        if auto_renewal_data is not UNSET:
            field_dict["auto_renewal_data"] = auto_renewal_data
        if proxy_password is not UNSET:
            field_dict["proxy_password"] = proxy_password
        if proxy_password_reset is not UNSET:
            field_dict["proxy_password_reset"] = proxy_password_reset
        if pools is not UNSET:
            field_dict["pools"] = pools
        if data is not UNSET:
            field_dict["data"] = data
        if data_spent is not UNSET:
            field_dict["data_spent"] = data_spent
        if latest_data_top_up is not UNSET:
            field_dict["latest_data_top_up"] = latest_data_top_up
        if latest_data_top_up_date is not UNSET:
            field_dict["latest_data_top_up_date"] = latest_data_top_up_date

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.order_ledgers_item import OrderLedgersItem
        from ..models.order_package import OrderPackage

        d = dict(src_dict)
        is_auto_renewal = d.pop("is_auto_renewal")

        package = OrderPackage.from_dict(d.pop("package"))

        data_remaining = d.pop("data_remaining")

        ledgers = []
        _ledgers = d.pop("ledgers")
        for ledgers_item_data in _ledgers:
            ledgers_item = OrderLedgersItem.from_dict(ledgers_item_data)

            ledgers.append(ledgers_item)

        data_updated = datetime.datetime.fromisoformat(d.pop("data_updated"))

        updated = datetime.datetime.fromisoformat(d.pop("updated"))

        created = datetime.datetime.fromisoformat(d.pop("created"))

        id = d.pop("id", UNSET)

        auto_renewal_percentage = d.pop("auto_renewal_percentage", UNSET)

        auto_renewal_data = d.pop("auto_renewal_data", UNSET)

        proxy_password = d.pop("proxy_password", UNSET)

        def _parse_proxy_password_reset(data: object) -> datetime.datetime | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                proxy_password_reset_type_0 = datetime.datetime.fromisoformat(data)

                return proxy_password_reset_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None | Unset, data)

        proxy_password_reset = _parse_proxy_password_reset(d.pop("proxy_password_reset", UNSET))

        pools = cast(list[str], d.pop("pools", UNSET))

        data = d.pop("data", UNSET)

        data_spent = d.pop("data_spent", UNSET)

        latest_data_top_up = d.pop("latest_data_top_up", UNSET)

        def _parse_latest_data_top_up_date(data: object) -> datetime.datetime | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                latest_data_top_up_date_type_0 = datetime.datetime.fromisoformat(data)

                return latest_data_top_up_date_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None | Unset, data)

        latest_data_top_up_date = _parse_latest_data_top_up_date(
            d.pop("latest_data_top_up_date", UNSET)
        )

        order = cls(
            is_auto_renewal=is_auto_renewal,
            package=package,
            data_remaining=data_remaining,
            ledgers=ledgers,
            data_updated=data_updated,
            updated=updated,
            created=created,
            id=id,
            auto_renewal_percentage=auto_renewal_percentage,
            auto_renewal_data=auto_renewal_data,
            proxy_password=proxy_password,
            proxy_password_reset=proxy_password_reset,
            pools=pools,
            data=data,
            data_spent=data_spent,
            latest_data_top_up=latest_data_top_up,
            latest_data_top_up_date=latest_data_top_up_date,
        )

        order.additional_properties = d
        return order

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
