# Generated by scripts/generate.py; do not edit.
from .api_keys import APIKeysResource
from .api_keys import AsyncAPIKeysResource
from .affiliates import AffiliatesResource
from .affiliates import AsyncAffiliatesResource
from .analytics import AnalyticsResource
from .analytics import AsyncAnalyticsResource
from .authorization import AuthorizationResource
from .authorization import AsyncAuthorizationResource
from .coupons import CouponsResource
from .coupons import AsyncCouponsResource
from .invoices import InvoicesResource
from .invoices import AsyncInvoicesResource
from .locations import LocationsResource
from .locations import AsyncLocationsResource
from .news import NewsResource
from .news import AsyncNewsResource
from .orders import OrdersResource
from .orders import AsyncOrdersResource
from .packages import PackagesResource
from .packages import AsyncPackagesResource
from .profile import ProfileResource
from .profile import AsyncProfileResource
from .proxies import ProxiesResource
from .proxies import AsyncProxiesResource
from .rewards import RewardsResource
from .rewards import AsyncRewardsResource
from .sessions import SessionsResource
from .sessions import AsyncSessionsResource
from .settings import SettingsResource
from .settings import AsyncSettingsResource
from .telegram import TelegramDashboardResource
from .telegram import AsyncTelegramDashboardResource
from .telegram_service import TelegramServiceResource
from .telegram_service import AsyncTelegramServiceResource
from .users import UsersResource
from .users import AsyncUsersResource
from .webhooks import WebhooksResource
from .webhooks import AsyncWebhooksResource

__all__ = [
    "APIKeysResource",
    "AsyncAPIKeysResource",
    "AffiliatesResource",
    "AsyncAffiliatesResource",
    "AnalyticsResource",
    "AsyncAnalyticsResource",
    "AuthorizationResource",
    "AsyncAuthorizationResource",
    "CouponsResource",
    "AsyncCouponsResource",
    "InvoicesResource",
    "AsyncInvoicesResource",
    "LocationsResource",
    "AsyncLocationsResource",
    "NewsResource",
    "AsyncNewsResource",
    "OrdersResource",
    "AsyncOrdersResource",
    "PackagesResource",
    "AsyncPackagesResource",
    "ProfileResource",
    "AsyncProfileResource",
    "ProxiesResource",
    "AsyncProxiesResource",
    "RewardsResource",
    "AsyncRewardsResource",
    "SessionsResource",
    "AsyncSessionsResource",
    "SettingsResource",
    "AsyncSettingsResource",
    "TelegramDashboardResource",
    "AsyncTelegramDashboardResource",
    "TelegramServiceResource",
    "AsyncTelegramServiceResource",
    "UsersResource",
    "AsyncUsersResource",
    "WebhooksResource",
    "AsyncWebhooksResource",
]
