# Generated by scripts/generate.py; do not edit.
from __future__ import annotations

from typing import Any, cast

from ..files import FileDownload
from .._generated.models.affiliate_stats_response import AffiliateStatsResponse
from .._generated.models.paginated_affiliate_list import PaginatedAffiliateList
from .._generated.models.paginated_affiliate_reward_list import PaginatedAffiliateRewardList
from .._generated.types import UNSET
from .._generated.types import Unset
from .._generated.api.affiliates import (
    affiliates_rewards_overall_retrieve as _affiliates_rewards_overall_retrieve,
)
from .._generated.api.affiliates import affiliates_list as _affiliates_list
from .._generated.api.affiliates import affiliates_rewards_list as _affiliates_rewards_list


class AffiliatesResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    def get_rewards_overall(
        self, *, accept_language: str | Unset = UNSET
    ) -> AffiliateStatsResponse:
        """Get affiliate earnings over time"""
        return cast(
            AffiliateStatsResponse,
            self._client._call(
                _affiliates_rewards_overall_retrieve.sync_detailed, accept_language=accept_language
            ),
        )

    def list(
        self,
        *,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedAffiliateList:
        """List referred customers"""
        return cast(
            PaginatedAffiliateList,
            self._client._call(
                _affiliates_list.sync_detailed,
                limit=limit,
                offset=offset,
                accept_language=accept_language,
            ),
        )

    def list_rewards(
        self,
        *,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedAffiliateRewardList:
        """List affiliate reward entries"""
        return cast(
            PaginatedAffiliateRewardList,
            self._client._call(
                _affiliates_rewards_list.sync_detailed,
                limit=limit,
                offset=offset,
                accept_language=accept_language,
            ),
        )


class AsyncAffiliatesResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    async def get_rewards_overall(
        self, *, accept_language: str | Unset = UNSET
    ) -> AffiliateStatsResponse:
        """Get affiliate earnings over time"""
        return cast(
            AffiliateStatsResponse,
            await self._client._call(
                _affiliates_rewards_overall_retrieve.asyncio_detailed,
                accept_language=accept_language,
            ),
        )

    async def list(
        self,
        *,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedAffiliateList:
        """List referred customers"""
        return cast(
            PaginatedAffiliateList,
            await self._client._call(
                _affiliates_list.asyncio_detailed,
                limit=limit,
                offset=offset,
                accept_language=accept_language,
            ),
        )

    async def list_rewards(
        self,
        *,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedAffiliateRewardList:
        """List affiliate reward entries"""
        return cast(
            PaginatedAffiliateRewardList,
            await self._client._call(
                _affiliates_rewards_list.asyncio_detailed,
                limit=limit,
                offset=offset,
                accept_language=accept_language,
            ),
        )
