# Generated by scripts/generate.py; do not edit.
from __future__ import annotations

from typing import Any, cast

from ..files import FileDownload
from .._generated.models.analytics_domains_retrieve_ordering import AnalyticsDomainsRetrieveOrdering
from .._generated.models.analytics_feed_retrieve_protocol import AnalyticsFeedRetrieveProtocol
from .._generated.models.analytics_logs_retrieve_protocol import AnalyticsLogsRetrieveProtocol
from .._generated.models.connections_response import ConnectionsResponse
from .._generated.models.domains_response import DomainsResponse
from .._generated.models.feed_response import FeedResponse
from .._generated.models.logs_response import LogsResponse
from .._generated.models.overall_response import OverallResponse
from .._generated.models.transactions_response import TransactionsResponse
from .._generated.types import UNSET
from uuid import UUID
from .._generated.types import Unset
import datetime
from .._generated.api.analytics import (
    analytics_connections_retrieve as _analytics_connections_retrieve,
)
from .._generated.api.analytics import analytics_overall_retrieve as _analytics_overall_retrieve
from .._generated.api.analytics import (
    analytics_transactions_retrieve as _analytics_transactions_retrieve,
)
from .._generated.api.analytics import analytics_domains_retrieve as _analytics_domains_retrieve
from .._generated.api.analytics import analytics_feed_retrieve as _analytics_feed_retrieve
from .._generated.api.analytics import analytics_logs_retrieve as _analytics_logs_retrieve


class AnalyticsResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    def get_connections(
        self,
        *,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        package_id: UUID | Unset = UNSET,
        user_id: UUID | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> ConnectionsResponse:
        """List active proxy connections"""
        return cast(
            ConnectionsResponse,
            self._client._call(
                _analytics_connections_retrieve.sync_detailed,
                limit=limit,
                offset=offset,
                package_id=package_id,
                user_id=user_id,
                accept_language=accept_language,
            ),
        )

    def get_overall(
        self,
        *,
        end: datetime.datetime | Unset = UNSET,
        include_sub_users: bool | Unset = False,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        package_id: UUID | Unset = UNSET,
        start: datetime.datetime | Unset = UNSET,
        timezone: str | Unset = UNSET,
        user_id: UUID | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> OverallResponse:
        """Get traffic totals over time"""
        return cast(
            OverallResponse,
            self._client._call(
                _analytics_overall_retrieve.sync_detailed,
                end=end,
                include_sub_users=include_sub_users,
                limit=limit,
                offset=offset,
                package_id=package_id,
                start=start,
                timezone=timezone,
                user_id=user_id,
                accept_language=accept_language,
            ),
        )

    def get_transactions(
        self,
        id: str,
        *,
        end: datetime.datetime | Unset = UNSET,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        recipient_id: UUID | Unset = UNSET,
        sender_id: UUID | Unset = UNSET,
        start: datetime.datetime | Unset = UNSET,
        timezone: str | Unset = UNSET,
        type_: int | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> TransactionsResponse:
        """List data transactions"""
        return cast(
            TransactionsResponse,
            self._client._call(
                _analytics_transactions_retrieve.sync_detailed,
                id=id,
                end=end,
                limit=limit,
                offset=offset,
                recipient_id=recipient_id,
                sender_id=sender_id,
                start=start,
                timezone=timezone,
                type_=type_,
                accept_language=accept_language,
            ),
        )

    def list_domains(
        self,
        *,
        end: datetime.datetime | Unset = UNSET,
        hostname: str | Unset = UNSET,
        include_sub_users: bool | Unset = False,
        ledger_id: UUID | Unset = UNSET,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: AnalyticsDomainsRetrieveOrdering
        | Unset = AnalyticsDomainsRetrieveOrdering.VALUE_0,
        package_id: UUID | Unset = UNSET,
        search: str | Unset = UNSET,
        start: datetime.datetime | Unset = UNSET,
        timezone: str | Unset = UNSET,
        user_id: UUID | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> DomainsResponse:
        """List top destination domains"""
        return cast(
            DomainsResponse,
            self._client._call(
                _analytics_domains_retrieve.sync_detailed,
                end=end,
                hostname=hostname,
                include_sub_users=include_sub_users,
                ledger_id=ledger_id,
                limit=limit,
                offset=offset,
                ordering=ordering,
                package_id=package_id,
                search=search,
                start=start,
                timezone=timezone,
                user_id=user_id,
                accept_language=accept_language,
            ),
        )

    def list_feed(
        self,
        *,
        city: str | Unset = UNSET,
        country: str | Unset = UNSET,
        end: datetime.datetime | Unset = UNSET,
        hostname: str | Unset = UNSET,
        ledger_id: UUID | Unset = UNSET,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        package_id: UUID | Unset = UNSET,
        protocol: AnalyticsFeedRetrieveProtocol | Unset = UNSET,
        region: str | Unset = UNSET,
        search: str | Unset = UNSET,
        start: datetime.datetime | Unset = UNSET,
        timezone: str | Unset = UNSET,
        user_id: UUID | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> FeedResponse:
        """List proxy request activity"""
        return cast(
            FeedResponse,
            self._client._call(
                _analytics_feed_retrieve.sync_detailed,
                city=city,
                country=country,
                end=end,
                hostname=hostname,
                ledger_id=ledger_id,
                limit=limit,
                offset=offset,
                package_id=package_id,
                protocol=protocol,
                region=region,
                search=search,
                start=start,
                timezone=timezone,
                user_id=user_id,
                accept_language=accept_language,
            ),
        )

    def list_logs(
        self,
        *,
        city: str | Unset = UNSET,
        country: str | Unset = UNSET,
        end: datetime.datetime | Unset = UNSET,
        error_code: int | Unset = UNSET,
        hostname: str | Unset = UNSET,
        ledger_id: UUID | Unset = UNSET,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        package_id: UUID | Unset = UNSET,
        protocol: AnalyticsLogsRetrieveProtocol | Unset = UNSET,
        region: str | Unset = UNSET,
        start: datetime.datetime | Unset = UNSET,
        timezone: str | Unset = UNSET,
        user_id: UUID | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> LogsResponse:
        """List proxy error logs"""
        return cast(
            LogsResponse,
            self._client._call(
                _analytics_logs_retrieve.sync_detailed,
                city=city,
                country=country,
                end=end,
                error_code=error_code,
                hostname=hostname,
                ledger_id=ledger_id,
                limit=limit,
                offset=offset,
                package_id=package_id,
                protocol=protocol,
                region=region,
                start=start,
                timezone=timezone,
                user_id=user_id,
                accept_language=accept_language,
            ),
        )


class AsyncAnalyticsResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    async def get_connections(
        self,
        *,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        package_id: UUID | Unset = UNSET,
        user_id: UUID | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> ConnectionsResponse:
        """List active proxy connections"""
        return cast(
            ConnectionsResponse,
            await self._client._call(
                _analytics_connections_retrieve.asyncio_detailed,
                limit=limit,
                offset=offset,
                package_id=package_id,
                user_id=user_id,
                accept_language=accept_language,
            ),
        )

    async def get_overall(
        self,
        *,
        end: datetime.datetime | Unset = UNSET,
        include_sub_users: bool | Unset = False,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        package_id: UUID | Unset = UNSET,
        start: datetime.datetime | Unset = UNSET,
        timezone: str | Unset = UNSET,
        user_id: UUID | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> OverallResponse:
        """Get traffic totals over time"""
        return cast(
            OverallResponse,
            await self._client._call(
                _analytics_overall_retrieve.asyncio_detailed,
                end=end,
                include_sub_users=include_sub_users,
                limit=limit,
                offset=offset,
                package_id=package_id,
                start=start,
                timezone=timezone,
                user_id=user_id,
                accept_language=accept_language,
            ),
        )

    async def get_transactions(
        self,
        id: str,
        *,
        end: datetime.datetime | Unset = UNSET,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        recipient_id: UUID | Unset = UNSET,
        sender_id: UUID | Unset = UNSET,
        start: datetime.datetime | Unset = UNSET,
        timezone: str | Unset = UNSET,
        type_: int | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> TransactionsResponse:
        """List data transactions"""
        return cast(
            TransactionsResponse,
            await self._client._call(
                _analytics_transactions_retrieve.asyncio_detailed,
                id=id,
                end=end,
                limit=limit,
                offset=offset,
                recipient_id=recipient_id,
                sender_id=sender_id,
                start=start,
                timezone=timezone,
                type_=type_,
                accept_language=accept_language,
            ),
        )

    async def list_domains(
        self,
        *,
        end: datetime.datetime | Unset = UNSET,
        hostname: str | Unset = UNSET,
        include_sub_users: bool | Unset = False,
        ledger_id: UUID | Unset = UNSET,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: AnalyticsDomainsRetrieveOrdering
        | Unset = AnalyticsDomainsRetrieveOrdering.VALUE_0,
        package_id: UUID | Unset = UNSET,
        search: str | Unset = UNSET,
        start: datetime.datetime | Unset = UNSET,
        timezone: str | Unset = UNSET,
        user_id: UUID | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> DomainsResponse:
        """List top destination domains"""
        return cast(
            DomainsResponse,
            await self._client._call(
                _analytics_domains_retrieve.asyncio_detailed,
                end=end,
                hostname=hostname,
                include_sub_users=include_sub_users,
                ledger_id=ledger_id,
                limit=limit,
                offset=offset,
                ordering=ordering,
                package_id=package_id,
                search=search,
                start=start,
                timezone=timezone,
                user_id=user_id,
                accept_language=accept_language,
            ),
        )

    async def list_feed(
        self,
        *,
        city: str | Unset = UNSET,
        country: str | Unset = UNSET,
        end: datetime.datetime | Unset = UNSET,
        hostname: str | Unset = UNSET,
        ledger_id: UUID | Unset = UNSET,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        package_id: UUID | Unset = UNSET,
        protocol: AnalyticsFeedRetrieveProtocol | Unset = UNSET,
        region: str | Unset = UNSET,
        search: str | Unset = UNSET,
        start: datetime.datetime | Unset = UNSET,
        timezone: str | Unset = UNSET,
        user_id: UUID | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> FeedResponse:
        """List proxy request activity"""
        return cast(
            FeedResponse,
            await self._client._call(
                _analytics_feed_retrieve.asyncio_detailed,
                city=city,
                country=country,
                end=end,
                hostname=hostname,
                ledger_id=ledger_id,
                limit=limit,
                offset=offset,
                package_id=package_id,
                protocol=protocol,
                region=region,
                search=search,
                start=start,
                timezone=timezone,
                user_id=user_id,
                accept_language=accept_language,
            ),
        )

    async def list_logs(
        self,
        *,
        city: str | Unset = UNSET,
        country: str | Unset = UNSET,
        end: datetime.datetime | Unset = UNSET,
        error_code: int | Unset = UNSET,
        hostname: str | Unset = UNSET,
        ledger_id: UUID | Unset = UNSET,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        package_id: UUID | Unset = UNSET,
        protocol: AnalyticsLogsRetrieveProtocol | Unset = UNSET,
        region: str | Unset = UNSET,
        start: datetime.datetime | Unset = UNSET,
        timezone: str | Unset = UNSET,
        user_id: UUID | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> LogsResponse:
        """List proxy error logs"""
        return cast(
            LogsResponse,
            await self._client._call(
                _analytics_logs_retrieve.asyncio_detailed,
                city=city,
                country=country,
                end=end,
                error_code=error_code,
                hostname=hostname,
                ledger_id=ledger_id,
                limit=limit,
                offset=offset,
                package_id=package_id,
                protocol=protocol,
                region=region,
                start=start,
                timezone=timezone,
                user_id=user_id,
                accept_language=accept_language,
            ),
        )
