# Generated by scripts/generate.py; do not edit.
from __future__ import annotations

from typing import Any, cast

from ..files import FileDownload
from .._generated.models.api_key_create import APIKeyCreate
from .._generated.models.api_key_create_request import APIKeyCreateRequest
from .._generated.models.paginated_api_key_list import PaginatedAPIKeyList
from .._generated.types import UNSET
from .._generated.types import Unset
from .._generated.api.api_keys import api_keys_create as _api_keys_create
from .._generated.api.api_keys import api_keys_destroy as _api_keys_destroy
from .._generated.api.api_keys import api_keys_list as _api_keys_list


class APIKeysResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    def create(
        self, *, body: APIKeyCreateRequest | Unset = UNSET, accept_language: str | Unset = UNSET
    ) -> APIKeyCreate:
        """Create an API key"""
        return cast(
            APIKeyCreate,
            self._client._call(
                _api_keys_create.sync_detailed, body=body, accept_language=accept_language
            ),
        )

    def delete(self, id: str, *, accept_language: str | Unset = UNSET) -> None:
        """Revoke an API key"""
        self._client._call(_api_keys_destroy.sync_detailed, id=id, accept_language=accept_language)
        return None

    def list(
        self,
        *,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedAPIKeyList:
        """List API keys"""
        return cast(
            PaginatedAPIKeyList,
            self._client._call(
                _api_keys_list.sync_detailed,
                limit=limit,
                offset=offset,
                accept_language=accept_language,
            ),
        )


class AsyncAPIKeysResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    async def create(
        self, *, body: APIKeyCreateRequest | Unset = UNSET, accept_language: str | Unset = UNSET
    ) -> APIKeyCreate:
        """Create an API key"""
        return cast(
            APIKeyCreate,
            await self._client._call(
                _api_keys_create.asyncio_detailed, body=body, accept_language=accept_language
            ),
        )

    async def delete(self, id: str, *, accept_language: str | Unset = UNSET) -> None:
        """Revoke an API key"""
        await self._client._call(
            _api_keys_destroy.asyncio_detailed, id=id, accept_language=accept_language
        )
        return None

    async def list(
        self,
        *,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedAPIKeyList:
        """List API keys"""
        return cast(
            PaginatedAPIKeyList,
            await self._client._call(
                _api_keys_list.asyncio_detailed,
                limit=limit,
                offset=offset,
                accept_language=accept_language,
            ),
        )
