# Generated by scripts/generate.py; do not edit.
from __future__ import annotations

from typing import Any, cast

from ..files import FileDownload
from .._generated.models.google_auth_request import GoogleAuthRequest
from .._generated.models.login_request import LoginRequest
from .._generated.models.password_recovery_response import PasswordRecoveryResponse
from .._generated.models.recover_password_request import RecoverPasswordRequest
from .._generated.models.sign_up_request import SignUpRequest
from .._generated.models.token_pair_response import TokenPairResponse
from .._generated.models.token_refresh_request import TokenRefreshRequest
from .._generated.models.token_refresh_response import TokenRefreshResponse
from .._generated.types import UNSET
from .._generated.types import Unset
from .._generated.api.authorization import login_create as _login_create
from .._generated.api.authorization import login_google_create as _login_google_create
from .._generated.api.authorization import recover_password_create as _recover_password_create
from .._generated.api.authorization import refresh_create as _refresh_create
from .._generated.api.authorization import signup_create as _signup_create


class AuthorizationResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    def login(
        self, *, body: LoginRequest, accept_language: str | Unset = UNSET
    ) -> TokenPairResponse:
        """Sign in with email or username"""
        return cast(
            TokenPairResponse,
            self._client._call(
                _login_create.sync_detailed, body=body, accept_language=accept_language
            ),
        )

    def login_with_google(
        self, *, body: GoogleAuthRequest, accept_language: str | Unset = UNSET
    ) -> TokenPairResponse:
        """Sign in with Google"""
        return cast(
            TokenPairResponse,
            self._client._call(
                _login_google_create.sync_detailed, body=body, accept_language=accept_language
            ),
        )

    def recover_password(
        self, *, body: RecoverPasswordRequest, accept_language: str | Unset = UNSET
    ) -> PasswordRecoveryResponse:
        """Send a password recovery email"""
        return cast(
            PasswordRecoveryResponse,
            self._client._call(
                _recover_password_create.sync_detailed, body=body, accept_language=accept_language
            ),
        )

    def refresh(
        self, *, body: TokenRefreshRequest, accept_language: str | Unset = UNSET
    ) -> TokenRefreshResponse:
        """Refresh an access token"""
        return cast(
            TokenRefreshResponse,
            self._client._call(
                _refresh_create.sync_detailed, body=body, accept_language=accept_language
            ),
        )

    def signup(
        self, *, body: SignUpRequest, accept_language: str | Unset = UNSET
    ) -> TokenPairResponse:
        """Create a customer account"""
        return cast(
            TokenPairResponse,
            self._client._call(
                _signup_create.sync_detailed, body=body, accept_language=accept_language
            ),
        )


class AsyncAuthorizationResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    async def login(
        self, *, body: LoginRequest, accept_language: str | Unset = UNSET
    ) -> TokenPairResponse:
        """Sign in with email or username"""
        return cast(
            TokenPairResponse,
            await self._client._call(
                _login_create.asyncio_detailed, body=body, accept_language=accept_language
            ),
        )

    async def login_with_google(
        self, *, body: GoogleAuthRequest, accept_language: str | Unset = UNSET
    ) -> TokenPairResponse:
        """Sign in with Google"""
        return cast(
            TokenPairResponse,
            await self._client._call(
                _login_google_create.asyncio_detailed, body=body, accept_language=accept_language
            ),
        )

    async def recover_password(
        self, *, body: RecoverPasswordRequest, accept_language: str | Unset = UNSET
    ) -> PasswordRecoveryResponse:
        """Send a password recovery email"""
        return cast(
            PasswordRecoveryResponse,
            await self._client._call(
                _recover_password_create.asyncio_detailed,
                body=body,
                accept_language=accept_language,
            ),
        )

    async def refresh(
        self, *, body: TokenRefreshRequest, accept_language: str | Unset = UNSET
    ) -> TokenRefreshResponse:
        """Refresh an access token"""
        return cast(
            TokenRefreshResponse,
            await self._client._call(
                _refresh_create.asyncio_detailed, body=body, accept_language=accept_language
            ),
        )

    async def signup(
        self, *, body: SignUpRequest, accept_language: str | Unset = UNSET
    ) -> TokenPairResponse:
        """Create a customer account"""
        return cast(
            TokenPairResponse,
            await self._client._call(
                _signup_create.asyncio_detailed, body=body, accept_language=accept_language
            ),
        )
