# Generated by scripts/generate.py; do not edit.
from __future__ import annotations

from typing import Any, cast

from ..files import FileDownload
from .._generated.models.invoice import Invoice
from .._generated.models.invoice_create_request import InvoiceCreateRequest
from .._generated.models.invoices_list_payment_gateway import InvoicesListPaymentGateway
from .._generated.models.invoices_list_status import InvoicesListStatus
from .._generated.models.invoices_list_type import InvoicesListType
from .._generated.models.paginated_invoice_list import PaginatedInvoiceList
from .._generated.models.payment_link_response import PaymentLinkResponse
from .._generated.types import UNSET
from uuid import UUID
from .._generated.types import Unset
from .._generated.api.invoices import invoices_create as _invoices_create
from .._generated.api.invoices import invoices_destroy as _invoices_destroy
from .._generated.api.invoices import (
    invoices_download_pdf_retrieve as _invoices_download_pdf_retrieve,
)
from .._generated.api.invoices import invoices_retrieve as _invoices_retrieve
from .._generated.api.invoices import invoices_pay_retrieve as _invoices_pay_retrieve
from .._generated.api.invoices import invoices_list as _invoices_list


class InvoicesResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    def create(
        self, *, body: InvoiceCreateRequest, accept_language: str | Unset = UNSET
    ) -> Invoice:
        """Create an invoice"""
        return cast(
            Invoice,
            self._client._call(
                _invoices_create.sync_detailed, body=body, accept_language=accept_language
            ),
        )

    def delete(self, id: str, *, accept_language: str | Unset = UNSET) -> None:
        """Delete an invoice"""
        self._client._call(_invoices_destroy.sync_detailed, id=id, accept_language=accept_language)
        return None

    def download_pdf(self, id: str, *, accept_language: str | Unset = UNSET) -> FileDownload:
        """Download an invoice PDF"""
        return cast(
            FileDownload,
            self._client._download(
                _invoices_download_pdf_retrieve.sync_detailed,
                id=id,
                accept_language=accept_language,
            ),
        )

    def get(self, id: str, *, accept_language: str | Unset = UNSET) -> Invoice:
        """Get an invoice"""
        return cast(
            Invoice,
            self._client._call(
                _invoices_retrieve.sync_detailed, id=id, accept_language=accept_language
            ),
        )

    def get_payment_link(
        self, id: str, *, accept_language: str | Unset = UNSET
    ) -> PaymentLinkResponse:
        """Get an invoice payment link"""
        return cast(
            PaymentLinkResponse,
            self._client._call(
                _invoices_pay_retrieve.sync_detailed, id=id, accept_language=accept_language
            ),
        )

    def list(
        self,
        *,
        gateway: InvoicesListPaymentGateway | Unset = UNSET,
        internal_id: str | Unset = UNSET,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        package_id: str | Unset = UNSET,
        search: str | Unset = UNSET,
        status: InvoicesListStatus | Unset = UNSET,
        type_: InvoicesListType | Unset = UNSET,
        user_email: str | Unset = UNSET,
        user_id: UUID | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedInvoiceList:
        """List invoices"""
        return cast(
            PaginatedInvoiceList,
            self._client._call(
                _invoices_list.sync_detailed,
                gateway=gateway,
                internal_id=internal_id,
                limit=limit,
                offset=offset,
                ordering=ordering,
                package_id=package_id,
                search=search,
                status=status,
                type_=type_,
                user_email=user_email,
                user_id=user_id,
                accept_language=accept_language,
            ),
        )


class AsyncInvoicesResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    async def create(
        self, *, body: InvoiceCreateRequest, accept_language: str | Unset = UNSET
    ) -> Invoice:
        """Create an invoice"""
        return cast(
            Invoice,
            await self._client._call(
                _invoices_create.asyncio_detailed, body=body, accept_language=accept_language
            ),
        )

    async def delete(self, id: str, *, accept_language: str | Unset = UNSET) -> None:
        """Delete an invoice"""
        await self._client._call(
            _invoices_destroy.asyncio_detailed, id=id, accept_language=accept_language
        )
        return None

    async def download_pdf(self, id: str, *, accept_language: str | Unset = UNSET) -> FileDownload:
        """Download an invoice PDF"""
        return cast(
            FileDownload,
            await self._client._download(
                _invoices_download_pdf_retrieve.asyncio_detailed,
                id=id,
                accept_language=accept_language,
            ),
        )

    async def get(self, id: str, *, accept_language: str | Unset = UNSET) -> Invoice:
        """Get an invoice"""
        return cast(
            Invoice,
            await self._client._call(
                _invoices_retrieve.asyncio_detailed, id=id, accept_language=accept_language
            ),
        )

    async def get_payment_link(
        self, id: str, *, accept_language: str | Unset = UNSET
    ) -> PaymentLinkResponse:
        """Get an invoice payment link"""
        return cast(
            PaymentLinkResponse,
            await self._client._call(
                _invoices_pay_retrieve.asyncio_detailed, id=id, accept_language=accept_language
            ),
        )

    async def list(
        self,
        *,
        gateway: InvoicesListPaymentGateway | Unset = UNSET,
        internal_id: str | Unset = UNSET,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        package_id: str | Unset = UNSET,
        search: str | Unset = UNSET,
        status: InvoicesListStatus | Unset = UNSET,
        type_: InvoicesListType | Unset = UNSET,
        user_email: str | Unset = UNSET,
        user_id: UUID | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedInvoiceList:
        """List invoices"""
        return cast(
            PaginatedInvoiceList,
            await self._client._call(
                _invoices_list.asyncio_detailed,
                gateway=gateway,
                internal_id=internal_id,
                limit=limit,
                offset=offset,
                ordering=ordering,
                package_id=package_id,
                search=search,
                status=status,
                type_=type_,
                user_email=user_email,
                user_id=user_id,
                accept_language=accept_language,
            ),
        )
