# Generated by scripts/generate.py; do not edit.
from __future__ import annotations

from typing import Any, cast

from ..files import FileDownload
from .._generated.models.city import City
from .._generated.models.continent import Continent
from .._generated.models.country import Country
from .._generated.models.paginated_city_list import PaginatedCityList
from .._generated.models.paginated_continent_list import PaginatedContinentList
from .._generated.models.paginated_country_list import PaginatedCountryList
from .._generated.models.paginated_isp_list import PaginatedISPList
from .._generated.models.paginated_location_asn_record_list import PaginatedLocationASNRecordList
from .._generated.models.paginated_region_list import PaginatedRegionList
from .._generated.models.region import Region
from .._generated.types import UNSET
from uuid import UUID
from .._generated.types import Unset
from .._generated.api.locations import locations_cities_retrieve as _locations_cities_retrieve
from .._generated.api.locations import (
    locations_continents_retrieve as _locations_continents_retrieve,
)
from .._generated.api.locations import locations_countries_retrieve as _locations_countries_retrieve
from .._generated.api.locations import locations_regions_retrieve as _locations_regions_retrieve
from .._generated.api.locations import locations_asn_list as _locations_asn_list
from .._generated.api.locations import locations_cities_list as _locations_cities_list
from .._generated.api.locations import locations_continents_list as _locations_continents_list
from .._generated.api.locations import locations_countries_list as _locations_countries_list
from .._generated.api.locations import locations_isps_list as _locations_isps_list
from .._generated.api.locations import locations_regions_list as _locations_regions_list


class LocationsResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    def get_city(self, id: str, *, accept_language: str | Unset = UNSET) -> City:
        """Get a city"""
        return cast(
            City,
            self._client._call(
                _locations_cities_retrieve.sync_detailed, id=id, accept_language=accept_language
            ),
        )

    def get_continent(self, id: str, *, accept_language: str | Unset = UNSET) -> Continent:
        """Get a continent"""
        return cast(
            Continent,
            self._client._call(
                _locations_continents_retrieve.sync_detailed, id=id, accept_language=accept_language
            ),
        )

    def get_country(self, id: str, *, accept_language: str | Unset = UNSET) -> Country:
        """Get a country"""
        return cast(
            Country,
            self._client._call(
                _locations_countries_retrieve.sync_detailed, id=id, accept_language=accept_language
            ),
        )

    def get_region(self, id: str, *, accept_language: str | Unset = UNSET) -> Region:
        """Get a region"""
        return cast(
            Region,
            self._client._call(
                _locations_regions_retrieve.sync_detailed, id=id, accept_language=accept_language
            ),
        )

    def list_asns(
        self,
        *,
        code: str | Unset = UNSET,
        country_code: str | Unset = UNSET,
        global_: bool | Unset = UNSET,
        limit: int | Unset = UNSET,
        name: str | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        package_id: UUID | Unset = UNSET,
        search: str | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedLocationASNRecordList:
        """List available autonomous systems"""
        return cast(
            PaginatedLocationASNRecordList,
            self._client._call(
                _locations_asn_list.sync_detailed,
                code=code,
                country_code=country_code,
                global_=global_,
                limit=limit,
                name=name,
                offset=offset,
                ordering=ordering,
                package_id=package_id,
                search=search,
                accept_language=accept_language,
            ),
        )

    def list_cities(
        self,
        *,
        code: str | Unset = UNSET,
        country_code: str | Unset = UNSET,
        limit: int | Unset = UNSET,
        name: str | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        package_id: UUID | Unset = UNSET,
        region_code: str | Unset = UNSET,
        search: str | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedCityList:
        """List available cities"""
        return cast(
            PaginatedCityList,
            self._client._call(
                _locations_cities_list.sync_detailed,
                code=code,
                country_code=country_code,
                limit=limit,
                name=name,
                offset=offset,
                ordering=ordering,
                package_id=package_id,
                region_code=region_code,
                search=search,
                accept_language=accept_language,
            ),
        )

    def list_continents(
        self,
        *,
        code: str | Unset = UNSET,
        limit: int | Unset = UNSET,
        name: str | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        package_id: UUID | Unset = UNSET,
        search: str | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedContinentList:
        """List available continents"""
        return cast(
            PaginatedContinentList,
            self._client._call(
                _locations_continents_list.sync_detailed,
                code=code,
                limit=limit,
                name=name,
                offset=offset,
                ordering=ordering,
                package_id=package_id,
                search=search,
                accept_language=accept_language,
            ),
        )

    def list_countries(
        self,
        *,
        code: str | Unset = UNSET,
        limit: int | Unset = UNSET,
        name: str | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        package_id: UUID | Unset = UNSET,
        search: str | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedCountryList:
        """List available countries"""
        return cast(
            PaginatedCountryList,
            self._client._call(
                _locations_countries_list.sync_detailed,
                code=code,
                limit=limit,
                name=name,
                offset=offset,
                ordering=ordering,
                package_id=package_id,
                search=search,
                accept_language=accept_language,
            ),
        )

    def list_isps(
        self,
        *,
        code: str | Unset = UNSET,
        country_code: str | Unset = UNSET,
        limit: int | Unset = UNSET,
        name: str | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        package_id: UUID | Unset = UNSET,
        search: str | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedISPList:
        """List available internet service providers"""
        return cast(
            PaginatedISPList,
            self._client._call(
                _locations_isps_list.sync_detailed,
                code=code,
                country_code=country_code,
                limit=limit,
                name=name,
                offset=offset,
                ordering=ordering,
                package_id=package_id,
                search=search,
                accept_language=accept_language,
            ),
        )

    def list_regions(
        self,
        *,
        code: str | Unset = UNSET,
        country_code: str | Unset = UNSET,
        limit: int | Unset = UNSET,
        name: str | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        package_id: UUID | Unset = UNSET,
        search: str | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedRegionList:
        """List available regions"""
        return cast(
            PaginatedRegionList,
            self._client._call(
                _locations_regions_list.sync_detailed,
                code=code,
                country_code=country_code,
                limit=limit,
                name=name,
                offset=offset,
                ordering=ordering,
                package_id=package_id,
                search=search,
                accept_language=accept_language,
            ),
        )


class AsyncLocationsResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    async def get_city(self, id: str, *, accept_language: str | Unset = UNSET) -> City:
        """Get a city"""
        return cast(
            City,
            await self._client._call(
                _locations_cities_retrieve.asyncio_detailed, id=id, accept_language=accept_language
            ),
        )

    async def get_continent(self, id: str, *, accept_language: str | Unset = UNSET) -> Continent:
        """Get a continent"""
        return cast(
            Continent,
            await self._client._call(
                _locations_continents_retrieve.asyncio_detailed,
                id=id,
                accept_language=accept_language,
            ),
        )

    async def get_country(self, id: str, *, accept_language: str | Unset = UNSET) -> Country:
        """Get a country"""
        return cast(
            Country,
            await self._client._call(
                _locations_countries_retrieve.asyncio_detailed,
                id=id,
                accept_language=accept_language,
            ),
        )

    async def get_region(self, id: str, *, accept_language: str | Unset = UNSET) -> Region:
        """Get a region"""
        return cast(
            Region,
            await self._client._call(
                _locations_regions_retrieve.asyncio_detailed, id=id, accept_language=accept_language
            ),
        )

    async def list_asns(
        self,
        *,
        code: str | Unset = UNSET,
        country_code: str | Unset = UNSET,
        global_: bool | Unset = UNSET,
        limit: int | Unset = UNSET,
        name: str | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        package_id: UUID | Unset = UNSET,
        search: str | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedLocationASNRecordList:
        """List available autonomous systems"""
        return cast(
            PaginatedLocationASNRecordList,
            await self._client._call(
                _locations_asn_list.asyncio_detailed,
                code=code,
                country_code=country_code,
                global_=global_,
                limit=limit,
                name=name,
                offset=offset,
                ordering=ordering,
                package_id=package_id,
                search=search,
                accept_language=accept_language,
            ),
        )

    async def list_cities(
        self,
        *,
        code: str | Unset = UNSET,
        country_code: str | Unset = UNSET,
        limit: int | Unset = UNSET,
        name: str | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        package_id: UUID | Unset = UNSET,
        region_code: str | Unset = UNSET,
        search: str | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedCityList:
        """List available cities"""
        return cast(
            PaginatedCityList,
            await self._client._call(
                _locations_cities_list.asyncio_detailed,
                code=code,
                country_code=country_code,
                limit=limit,
                name=name,
                offset=offset,
                ordering=ordering,
                package_id=package_id,
                region_code=region_code,
                search=search,
                accept_language=accept_language,
            ),
        )

    async def list_continents(
        self,
        *,
        code: str | Unset = UNSET,
        limit: int | Unset = UNSET,
        name: str | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        package_id: UUID | Unset = UNSET,
        search: str | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedContinentList:
        """List available continents"""
        return cast(
            PaginatedContinentList,
            await self._client._call(
                _locations_continents_list.asyncio_detailed,
                code=code,
                limit=limit,
                name=name,
                offset=offset,
                ordering=ordering,
                package_id=package_id,
                search=search,
                accept_language=accept_language,
            ),
        )

    async def list_countries(
        self,
        *,
        code: str | Unset = UNSET,
        limit: int | Unset = UNSET,
        name: str | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        package_id: UUID | Unset = UNSET,
        search: str | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedCountryList:
        """List available countries"""
        return cast(
            PaginatedCountryList,
            await self._client._call(
                _locations_countries_list.asyncio_detailed,
                code=code,
                limit=limit,
                name=name,
                offset=offset,
                ordering=ordering,
                package_id=package_id,
                search=search,
                accept_language=accept_language,
            ),
        )

    async def list_isps(
        self,
        *,
        code: str | Unset = UNSET,
        country_code: str | Unset = UNSET,
        limit: int | Unset = UNSET,
        name: str | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        package_id: UUID | Unset = UNSET,
        search: str | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedISPList:
        """List available internet service providers"""
        return cast(
            PaginatedISPList,
            await self._client._call(
                _locations_isps_list.asyncio_detailed,
                code=code,
                country_code=country_code,
                limit=limit,
                name=name,
                offset=offset,
                ordering=ordering,
                package_id=package_id,
                search=search,
                accept_language=accept_language,
            ),
        )

    async def list_regions(
        self,
        *,
        code: str | Unset = UNSET,
        country_code: str | Unset = UNSET,
        limit: int | Unset = UNSET,
        name: str | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        package_id: UUID | Unset = UNSET,
        search: str | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedRegionList:
        """List available regions"""
        return cast(
            PaginatedRegionList,
            await self._client._call(
                _locations_regions_list.asyncio_detailed,
                code=code,
                country_code=country_code,
                limit=limit,
                name=name,
                offset=offset,
                ordering=ordering,
                package_id=package_id,
                search=search,
                accept_language=accept_language,
            ),
        )
