# Generated by scripts/generate.py; do not edit.
from __future__ import annotations

from typing import Any, cast

from ..files import FileDownload
from .._generated.models.paginated_news_list import PaginatedNewsList
from .._generated.types import UNSET
from .._generated.types import Unset
from .._generated.api.news import news_list as _news_list


class NewsResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    def list(
        self,
        *,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        search: str | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedNewsList:
        """List product announcements"""
        return cast(
            PaginatedNewsList,
            self._client._call(
                _news_list.sync_detailed,
                limit=limit,
                offset=offset,
                ordering=ordering,
                search=search,
                accept_language=accept_language,
            ),
        )


class AsyncNewsResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    async def list(
        self,
        *,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        search: str | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedNewsList:
        """List product announcements"""
        return cast(
            PaginatedNewsList,
            await self._client._call(
                _news_list.asyncio_detailed,
                limit=limit,
                offset=offset,
                ordering=ordering,
                search=search,
                accept_language=accept_language,
            ),
        )
