# Generated by scripts/generate.py; do not edit.
from __future__ import annotations

from typing import Any, cast

from ..files import FileDownload
from .._generated.models.order import Order
from .._generated.models.order_detailed import OrderDetailed
from .._generated.models.orders_list_package_type import OrdersListPackageType
from .._generated.models.paginated_order_list import PaginatedOrderList
from .._generated.models.patched_order_auto_renewal_request import PatchedOrderAutoRenewalRequest
from .._generated.models.proxy_password_reset_response import ProxyPasswordResetResponse
from .._generated.models.reset_password_request import ResetPasswordRequest
from .._generated.types import UNSET
from uuid import UUID
from .._generated.types import Unset
from .._generated.api.orders import orders_destroy as _orders_destroy
from .._generated.api.orders import orders_retrieve as _orders_retrieve
from .._generated.api.orders import orders_list as _orders_list
from .._generated.api.orders import reset_password_create as _reset_password_create
from .._generated.api.orders import orders_partial_update as _orders_partial_update


class OrdersResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    def delete(self, id: str, *, accept_language: str | Unset = UNSET) -> None:
        """Delete a sub-user order"""
        self._client._call(_orders_destroy.sync_detailed, id=id, accept_language=accept_language)
        return None

    def get(self, id: str, *, accept_language: str | Unset = UNSET) -> OrderDetailed:
        """Get an order"""
        return cast(
            OrderDetailed,
            self._client._call(
                _orders_retrieve.sync_detailed, id=id, accept_language=accept_language
            ),
        )

    def list(
        self,
        *,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        package_alias: str | Unset = UNSET,
        package_id: str | Unset = UNSET,
        package_type: OrdersListPackageType | Unset = UNSET,
        search: str | Unset = UNSET,
        user_email: str | Unset = UNSET,
        user_id: UUID | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedOrderList:
        """List active orders"""
        return cast(
            PaginatedOrderList,
            self._client._call(
                _orders_list.sync_detailed,
                limit=limit,
                offset=offset,
                ordering=ordering,
                package_alias=package_alias,
                package_id=package_id,
                package_type=package_type,
                search=search,
                user_email=user_email,
                user_id=user_id,
                accept_language=accept_language,
            ),
        )

    def reset_password(
        self, *, body: ResetPasswordRequest, accept_language: str | Unset = UNSET
    ) -> ProxyPasswordResetResponse:
        """Reset an order's proxy password"""
        return cast(
            ProxyPasswordResetResponse,
            self._client._call(
                _reset_password_create.sync_detailed, body=body, accept_language=accept_language
            ),
        )

    def update_auto_renewal(
        self,
        id: str,
        *,
        body: PatchedOrderAutoRenewalRequest | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> Order:
        """Update order auto-renewal"""
        return cast(
            Order,
            self._client._call(
                _orders_partial_update.sync_detailed,
                id=id,
                body=body,
                accept_language=accept_language,
            ),
        )


class AsyncOrdersResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    async def delete(self, id: str, *, accept_language: str | Unset = UNSET) -> None:
        """Delete a sub-user order"""
        await self._client._call(
            _orders_destroy.asyncio_detailed, id=id, accept_language=accept_language
        )
        return None

    async def get(self, id: str, *, accept_language: str | Unset = UNSET) -> OrderDetailed:
        """Get an order"""
        return cast(
            OrderDetailed,
            await self._client._call(
                _orders_retrieve.asyncio_detailed, id=id, accept_language=accept_language
            ),
        )

    async def list(
        self,
        *,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        package_alias: str | Unset = UNSET,
        package_id: str | Unset = UNSET,
        package_type: OrdersListPackageType | Unset = UNSET,
        search: str | Unset = UNSET,
        user_email: str | Unset = UNSET,
        user_id: UUID | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedOrderList:
        """List active orders"""
        return cast(
            PaginatedOrderList,
            await self._client._call(
                _orders_list.asyncio_detailed,
                limit=limit,
                offset=offset,
                ordering=ordering,
                package_alias=package_alias,
                package_id=package_id,
                package_type=package_type,
                search=search,
                user_email=user_email,
                user_id=user_id,
                accept_language=accept_language,
            ),
        )

    async def reset_password(
        self, *, body: ResetPasswordRequest, accept_language: str | Unset = UNSET
    ) -> ProxyPasswordResetResponse:
        """Reset an order's proxy password"""
        return cast(
            ProxyPasswordResetResponse,
            await self._client._call(
                _reset_password_create.asyncio_detailed, body=body, accept_language=accept_language
            ),
        )

    async def update_auto_renewal(
        self,
        id: str,
        *,
        body: PatchedOrderAutoRenewalRequest | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> Order:
        """Update order auto-renewal"""
        return cast(
            Order,
            await self._client._call(
                _orders_partial_update.asyncio_detailed,
                id=id,
                body=body,
                accept_language=accept_language,
            ),
        )
