# Generated by scripts/generate.py; do not edit.
from __future__ import annotations

from typing import Any, cast

from ..files import FileDownload
from .._generated.models.packages_commissions_list_pricing_unit import (
    PackagesCommissionsListPricingUnit,
)
from .._generated.models.packages_commissions_list_type import PackagesCommissionsListType
from .._generated.models.packages_list_pricing_unit import PackagesListPricingUnit
from .._generated.models.packages_list_type import PackagesListType
from .._generated.models.paginated_package_commission_list import PaginatedPackageCommissionList
from .._generated.models.paginated_package_list import PaginatedPackageList
from .._generated.types import UNSET
from .._generated.types import Unset
from .._generated.api.packages import packages_list as _packages_list
from .._generated.api.packages import packages_commissions_list as _packages_commissions_list


class PackagesResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    def list(
        self,
        *,
        alias: str | Unset = UNSET,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        pricing_unit: PackagesListPricingUnit | Unset = UNSET,
        search: str | Unset = UNSET,
        type_: PackagesListType | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedPackageList:
        """List available proxy packages"""
        return cast(
            PaginatedPackageList,
            self._client._call(
                _packages_list.sync_detailed,
                alias=alias,
                limit=limit,
                offset=offset,
                ordering=ordering,
                pricing_unit=pricing_unit,
                search=search,
                type_=type_,
                accept_language=accept_language,
            ),
        )

    def list_commissions(
        self,
        *,
        alias: str | Unset = UNSET,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        pricing_unit: PackagesCommissionsListPricingUnit | Unset = UNSET,
        type_: PackagesCommissionsListType | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedPackageCommissionList:
        """List affiliate package commissions"""
        return cast(
            PaginatedPackageCommissionList,
            self._client._call(
                _packages_commissions_list.sync_detailed,
                alias=alias,
                limit=limit,
                offset=offset,
                ordering=ordering,
                pricing_unit=pricing_unit,
                type_=type_,
                accept_language=accept_language,
            ),
        )


class AsyncPackagesResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    async def list(
        self,
        *,
        alias: str | Unset = UNSET,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        pricing_unit: PackagesListPricingUnit | Unset = UNSET,
        search: str | Unset = UNSET,
        type_: PackagesListType | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedPackageList:
        """List available proxy packages"""
        return cast(
            PaginatedPackageList,
            await self._client._call(
                _packages_list.asyncio_detailed,
                alias=alias,
                limit=limit,
                offset=offset,
                ordering=ordering,
                pricing_unit=pricing_unit,
                search=search,
                type_=type_,
                accept_language=accept_language,
            ),
        )

    async def list_commissions(
        self,
        *,
        alias: str | Unset = UNSET,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        pricing_unit: PackagesCommissionsListPricingUnit | Unset = UNSET,
        type_: PackagesCommissionsListType | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedPackageCommissionList:
        """List affiliate package commissions"""
        return cast(
            PaginatedPackageCommissionList,
            await self._client._call(
                _packages_commissions_list.asyncio_detailed,
                alias=alias,
                limit=limit,
                offset=offset,
                ordering=ordering,
                pricing_unit=pricing_unit,
                type_=type_,
                accept_language=accept_language,
            ),
        )
