# Generated by scripts/generate.py; do not edit.
from __future__ import annotations

from typing import Any, cast

from ..files import FileDownload
from ..response import ApiResponse
from .._generated.models.change_password_request import ChangePasswordRequest
from .._generated.models.enabled_response import EnabledResponse
from .._generated.models.message_response import MessageResponse
from .._generated.models.patched_profile_update_request import PatchedProfileUpdateRequest
from .._generated.models.two_factor_confirm_request import TwoFactorConfirmRequest
from .._generated.models.two_factor_disable_request import TwoFactorDisableRequest
from .._generated.models.two_factor_setup_request_request import TwoFactorSetupRequestRequest
from .._generated.models.two_factor_setup_response import TwoFactorSetupResponse
from .._generated.types import UNSET
from .._generated.types import Unset
from .._generated.models.user import User
from .._generated.api.profile import (
    profile_change_password_create as _profile_change_password_create,
)
from .._generated.api.profile import profile_2fa_confirm_create as _profile_2fa_confirm_create
from .._generated.api.profile import profile_destroy as _profile_destroy
from .._generated.api.profile import profile_2fa_disable_create as _profile_2fa_disable_create
from .._generated.api.profile import profile_retrieve as _profile_retrieve
from .._generated.api.profile import profile_2fa_status_retrieve as _profile_2fa_status_retrieve
from .._generated.api.profile import profile_2fa_setup_create as _profile_2fa_setup_create
from .._generated.api.profile import profile_partial_update as _profile_partial_update


class ProfileResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    def change_password(
        self, *, body: ChangePasswordRequest, accept_language: str | Unset = UNSET
    ) -> MessageResponse:
        """Change the account password"""
        return cast(
            MessageResponse,
            self._client._call(
                _profile_change_password_create.sync_detailed,
                body=body,
                accept_language=accept_language,
            ),
        )

    def change_password_with_response(
        self, *, body: ChangePasswordRequest, accept_language: str | Unset = UNSET
    ) -> ApiResponse[MessageResponse]:
        """Change the account password; include response metadata."""
        return cast(
            ApiResponse[MessageResponse],
            self._client._call_with_response(
                _profile_change_password_create.sync_detailed,
                body=body,
                accept_language=accept_language,
            ),
        )

    def confirm_two_factor(
        self, *, body: TwoFactorConfirmRequest, accept_language: str | Unset = UNSET
    ) -> EnabledResponse:
        """Confirm two-factor authentication"""
        return cast(
            EnabledResponse,
            self._client._call(
                _profile_2fa_confirm_create.sync_detailed,
                body=body,
                accept_language=accept_language,
            ),
        )

    def confirm_two_factor_with_response(
        self, *, body: TwoFactorConfirmRequest, accept_language: str | Unset = UNSET
    ) -> ApiResponse[EnabledResponse]:
        """Confirm two-factor authentication; include response metadata."""
        return cast(
            ApiResponse[EnabledResponse],
            self._client._call_with_response(
                _profile_2fa_confirm_create.sync_detailed,
                body=body,
                accept_language=accept_language,
            ),
        )

    def delete(
        self, *, if_match: str | Unset = UNSET, accept_language: str | Unset = UNSET
    ) -> None:
        """Delete the current account"""
        self._client._call(
            _profile_destroy.sync_detailed, if_match=if_match, accept_language=accept_language
        )
        return None

    def delete_with_response(
        self, *, if_match: str | Unset = UNSET, accept_language: str | Unset = UNSET
    ) -> ApiResponse[None]:
        """Delete the current account; include response metadata."""
        return cast(
            ApiResponse[None],
            self._client._call_with_response(
                _profile_destroy.sync_detailed, if_match=if_match, accept_language=accept_language
            ),
        )

    def disable_two_factor(
        self, *, body: TwoFactorDisableRequest, accept_language: str | Unset = UNSET
    ) -> EnabledResponse:
        """Disable two-factor authentication"""
        return cast(
            EnabledResponse,
            self._client._call(
                _profile_2fa_disable_create.sync_detailed,
                body=body,
                accept_language=accept_language,
            ),
        )

    def disable_two_factor_with_response(
        self, *, body: TwoFactorDisableRequest, accept_language: str | Unset = UNSET
    ) -> ApiResponse[EnabledResponse]:
        """Disable two-factor authentication; include response metadata."""
        return cast(
            ApiResponse[EnabledResponse],
            self._client._call_with_response(
                _profile_2fa_disable_create.sync_detailed,
                body=body,
                accept_language=accept_language,
            ),
        )

    def get(self, *, accept_language: str | Unset = UNSET) -> User:
        """Get the current profile"""
        return cast(
            User,
            self._client._call(_profile_retrieve.sync_detailed, accept_language=accept_language),
        )

    def get_with_response(self, *, accept_language: str | Unset = UNSET) -> ApiResponse[User]:
        """Get the current profile; include response metadata."""
        return cast(
            ApiResponse[User],
            self._client._call_with_response(
                _profile_retrieve.sync_detailed, accept_language=accept_language
            ),
        )

    def get_two_factor_status(self, *, accept_language: str | Unset = UNSET) -> EnabledResponse:
        """Get two-factor status"""
        return cast(
            EnabledResponse,
            self._client._call(
                _profile_2fa_status_retrieve.sync_detailed, accept_language=accept_language
            ),
        )

    def get_two_factor_status_with_response(
        self, *, accept_language: str | Unset = UNSET
    ) -> ApiResponse[EnabledResponse]:
        """Get two-factor status; include response metadata."""
        return cast(
            ApiResponse[EnabledResponse],
            self._client._call_with_response(
                _profile_2fa_status_retrieve.sync_detailed, accept_language=accept_language
            ),
        )

    def setup_two_factor(
        self,
        *,
        body: TwoFactorSetupRequestRequest | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> TwoFactorSetupResponse:
        """Prepare two-factor authentication"""
        return cast(
            TwoFactorSetupResponse,
            self._client._call(
                _profile_2fa_setup_create.sync_detailed, body=body, accept_language=accept_language
            ),
        )

    def setup_two_factor_with_response(
        self,
        *,
        body: TwoFactorSetupRequestRequest | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> ApiResponse[TwoFactorSetupResponse]:
        """Prepare two-factor authentication; include response metadata."""
        return cast(
            ApiResponse[TwoFactorSetupResponse],
            self._client._call_with_response(
                _profile_2fa_setup_create.sync_detailed, body=body, accept_language=accept_language
            ),
        )

    def update(
        self,
        *,
        body: PatchedProfileUpdateRequest | Unset = UNSET,
        if_match: str | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> User:
        """Update the current profile"""
        return cast(
            User,
            self._client._call(
                _profile_partial_update.sync_detailed,
                body=body,
                if_match=if_match,
                accept_language=accept_language,
            ),
        )

    def update_with_response(
        self,
        *,
        body: PatchedProfileUpdateRequest | Unset = UNSET,
        if_match: str | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> ApiResponse[User]:
        """Update the current profile; include response metadata."""
        return cast(
            ApiResponse[User],
            self._client._call_with_response(
                _profile_partial_update.sync_detailed,
                body=body,
                if_match=if_match,
                accept_language=accept_language,
            ),
        )


class AsyncProfileResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    async def change_password(
        self, *, body: ChangePasswordRequest, accept_language: str | Unset = UNSET
    ) -> MessageResponse:
        """Change the account password"""
        return cast(
            MessageResponse,
            await self._client._call(
                _profile_change_password_create.asyncio_detailed,
                body=body,
                accept_language=accept_language,
            ),
        )

    async def change_password_with_response(
        self, *, body: ChangePasswordRequest, accept_language: str | Unset = UNSET
    ) -> ApiResponse[MessageResponse]:
        """Change the account password; include response metadata."""
        return cast(
            ApiResponse[MessageResponse],
            await self._client._call_with_response(
                _profile_change_password_create.asyncio_detailed,
                body=body,
                accept_language=accept_language,
            ),
        )

    async def confirm_two_factor(
        self, *, body: TwoFactorConfirmRequest, accept_language: str | Unset = UNSET
    ) -> EnabledResponse:
        """Confirm two-factor authentication"""
        return cast(
            EnabledResponse,
            await self._client._call(
                _profile_2fa_confirm_create.asyncio_detailed,
                body=body,
                accept_language=accept_language,
            ),
        )

    async def confirm_two_factor_with_response(
        self, *, body: TwoFactorConfirmRequest, accept_language: str | Unset = UNSET
    ) -> ApiResponse[EnabledResponse]:
        """Confirm two-factor authentication; include response metadata."""
        return cast(
            ApiResponse[EnabledResponse],
            await self._client._call_with_response(
                _profile_2fa_confirm_create.asyncio_detailed,
                body=body,
                accept_language=accept_language,
            ),
        )

    async def delete(
        self, *, if_match: str | Unset = UNSET, accept_language: str | Unset = UNSET
    ) -> None:
        """Delete the current account"""
        await self._client._call(
            _profile_destroy.asyncio_detailed, if_match=if_match, accept_language=accept_language
        )
        return None

    async def delete_with_response(
        self, *, if_match: str | Unset = UNSET, accept_language: str | Unset = UNSET
    ) -> ApiResponse[None]:
        """Delete the current account; include response metadata."""
        return cast(
            ApiResponse[None],
            await self._client._call_with_response(
                _profile_destroy.asyncio_detailed,
                if_match=if_match,
                accept_language=accept_language,
            ),
        )

    async def disable_two_factor(
        self, *, body: TwoFactorDisableRequest, accept_language: str | Unset = UNSET
    ) -> EnabledResponse:
        """Disable two-factor authentication"""
        return cast(
            EnabledResponse,
            await self._client._call(
                _profile_2fa_disable_create.asyncio_detailed,
                body=body,
                accept_language=accept_language,
            ),
        )

    async def disable_two_factor_with_response(
        self, *, body: TwoFactorDisableRequest, accept_language: str | Unset = UNSET
    ) -> ApiResponse[EnabledResponse]:
        """Disable two-factor authentication; include response metadata."""
        return cast(
            ApiResponse[EnabledResponse],
            await self._client._call_with_response(
                _profile_2fa_disable_create.asyncio_detailed,
                body=body,
                accept_language=accept_language,
            ),
        )

    async def get(self, *, accept_language: str | Unset = UNSET) -> User:
        """Get the current profile"""
        return cast(
            User,
            await self._client._call(
                _profile_retrieve.asyncio_detailed, accept_language=accept_language
            ),
        )

    async def get_with_response(self, *, accept_language: str | Unset = UNSET) -> ApiResponse[User]:
        """Get the current profile; include response metadata."""
        return cast(
            ApiResponse[User],
            await self._client._call_with_response(
                _profile_retrieve.asyncio_detailed, accept_language=accept_language
            ),
        )

    async def get_two_factor_status(
        self, *, accept_language: str | Unset = UNSET
    ) -> EnabledResponse:
        """Get two-factor status"""
        return cast(
            EnabledResponse,
            await self._client._call(
                _profile_2fa_status_retrieve.asyncio_detailed, accept_language=accept_language
            ),
        )

    async def get_two_factor_status_with_response(
        self, *, accept_language: str | Unset = UNSET
    ) -> ApiResponse[EnabledResponse]:
        """Get two-factor status; include response metadata."""
        return cast(
            ApiResponse[EnabledResponse],
            await self._client._call_with_response(
                _profile_2fa_status_retrieve.asyncio_detailed, accept_language=accept_language
            ),
        )

    async def setup_two_factor(
        self,
        *,
        body: TwoFactorSetupRequestRequest | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> TwoFactorSetupResponse:
        """Prepare two-factor authentication"""
        return cast(
            TwoFactorSetupResponse,
            await self._client._call(
                _profile_2fa_setup_create.asyncio_detailed,
                body=body,
                accept_language=accept_language,
            ),
        )

    async def setup_two_factor_with_response(
        self,
        *,
        body: TwoFactorSetupRequestRequest | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> ApiResponse[TwoFactorSetupResponse]:
        """Prepare two-factor authentication; include response metadata."""
        return cast(
            ApiResponse[TwoFactorSetupResponse],
            await self._client._call_with_response(
                _profile_2fa_setup_create.asyncio_detailed,
                body=body,
                accept_language=accept_language,
            ),
        )

    async def update(
        self,
        *,
        body: PatchedProfileUpdateRequest | Unset = UNSET,
        if_match: str | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> User:
        """Update the current profile"""
        return cast(
            User,
            await self._client._call(
                _profile_partial_update.asyncio_detailed,
                body=body,
                if_match=if_match,
                accept_language=accept_language,
            ),
        )

    async def update_with_response(
        self,
        *,
        body: PatchedProfileUpdateRequest | Unset = UNSET,
        if_match: str | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> ApiResponse[User]:
        """Update the current profile; include response metadata."""
        return cast(
            ApiResponse[User],
            await self._client._call_with_response(
                _profile_partial_update.asyncio_detailed,
                body=body,
                if_match=if_match,
                accept_language=accept_language,
            ),
        )
