# Generated by scripts/generate.py; do not edit.
from __future__ import annotations

from typing import Any, cast

from ..files import FileDownload
from ..response import ApiResponse
from .._generated.models.paginated_provider_data_balance_list import (
    PaginatedProviderDataBalanceList,
)
from .._generated.types import UNSET
from .._generated.types import Unset
from .._generated.api.providers import providers_data_balances_list as _providers_data_balances_list


class ProvidersResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    def list_data_balances(
        self,
        *,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedProviderDataBalanceList:
        """List provider data balances"""
        return cast(
            PaginatedProviderDataBalanceList,
            self._client._call(
                _providers_data_balances_list.sync_detailed,
                limit=limit,
                offset=offset,
                accept_language=accept_language,
            ),
        )

    def list_data_balances_with_response(
        self,
        *,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> ApiResponse[PaginatedProviderDataBalanceList]:
        """List provider data balances; include response metadata."""
        return cast(
            ApiResponse[PaginatedProviderDataBalanceList],
            self._client._call_with_response(
                _providers_data_balances_list.sync_detailed,
                limit=limit,
                offset=offset,
                accept_language=accept_language,
            ),
        )


class AsyncProvidersResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    async def list_data_balances(
        self,
        *,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedProviderDataBalanceList:
        """List provider data balances"""
        return cast(
            PaginatedProviderDataBalanceList,
            await self._client._call(
                _providers_data_balances_list.asyncio_detailed,
                limit=limit,
                offset=offset,
                accept_language=accept_language,
            ),
        )

    async def list_data_balances_with_response(
        self,
        *,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> ApiResponse[PaginatedProviderDataBalanceList]:
        """List provider data balances; include response metadata."""
        return cast(
            ApiResponse[PaginatedProviderDataBalanceList],
            await self._client._call_with_response(
                _providers_data_balances_list.asyncio_detailed,
                limit=limit,
                offset=offset,
                accept_language=accept_language,
            ),
        )
