# Generated by scripts/generate.py; do not edit.
from __future__ import annotations

from typing import Any, cast

from ..files import FileDownload
from .._generated.models.generate_proxy_request import GenerateProxyRequest
from .._generated.models.generate_proxy_response import GenerateProxyResponse
from .._generated.types import UNSET
from .._generated.types import Unset
from .._generated.api.proxies import proxies_generate_create as _proxies_generate_create


class ProxiesResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    def generate(
        self, *, body: GenerateProxyRequest, accept_language: str | Unset = UNSET
    ) -> GenerateProxyResponse:
        """Generate proxy credentials"""
        return cast(
            GenerateProxyResponse,
            self._client._call(
                _proxies_generate_create.sync_detailed, body=body, accept_language=accept_language
            ),
        )


class AsyncProxiesResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    async def generate(
        self, *, body: GenerateProxyRequest, accept_language: str | Unset = UNSET
    ) -> GenerateProxyResponse:
        """Generate proxy credentials"""
        return cast(
            GenerateProxyResponse,
            await self._client._call(
                _proxies_generate_create.asyncio_detailed,
                body=body,
                accept_language=accept_language,
            ),
        )
