# Generated by scripts/generate.py; do not edit.
from __future__ import annotations

from typing import Any, cast

from ..files import FileDownload
from ..response import ApiResponse
from .._generated.models.paginated_reward_list import PaginatedRewardList
from .._generated.models.reward_claim_request import RewardClaimRequest
from .._generated.models.rewards_list_level import RewardsListLevel
from .._generated.types import UNSET
from uuid import UUID
from .._generated.types import Unset
from .._generated.api.rewards import rewards_claim_create as _rewards_claim_create
from .._generated.api.rewards import rewards_list as _rewards_list


class RewardsResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    def claim(self, *, body: RewardClaimRequest, accept_language: str | Unset = UNSET) -> None:
        """Claim available rewards"""
        self._client._call(
            _rewards_claim_create.sync_detailed, body=body, accept_language=accept_language
        )
        return None

    def claim_with_response(
        self, *, body: RewardClaimRequest, accept_language: str | Unset = UNSET
    ) -> ApiResponse[None]:
        """Claim available rewards; include response metadata."""
        return cast(
            ApiResponse[None],
            self._client._call_with_response(
                _rewards_claim_create.sync_detailed, body=body, accept_language=accept_language
            ),
        )

    def list(
        self,
        *,
        level: RewardsListLevel | Unset = UNSET,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        user_email: str | Unset = UNSET,
        user_id: UUID | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedRewardList:
        """List account rewards"""
        return cast(
            PaginatedRewardList,
            self._client._call(
                _rewards_list.sync_detailed,
                level=level,
                limit=limit,
                offset=offset,
                ordering=ordering,
                user_email=user_email,
                user_id=user_id,
                accept_language=accept_language,
            ),
        )

    def list_with_response(
        self,
        *,
        level: RewardsListLevel | Unset = UNSET,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        user_email: str | Unset = UNSET,
        user_id: UUID | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> ApiResponse[PaginatedRewardList]:
        """List account rewards; include response metadata."""
        return cast(
            ApiResponse[PaginatedRewardList],
            self._client._call_with_response(
                _rewards_list.sync_detailed,
                level=level,
                limit=limit,
                offset=offset,
                ordering=ordering,
                user_email=user_email,
                user_id=user_id,
                accept_language=accept_language,
            ),
        )


class AsyncRewardsResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    async def claim(
        self, *, body: RewardClaimRequest, accept_language: str | Unset = UNSET
    ) -> None:
        """Claim available rewards"""
        await self._client._call(
            _rewards_claim_create.asyncio_detailed, body=body, accept_language=accept_language
        )
        return None

    async def claim_with_response(
        self, *, body: RewardClaimRequest, accept_language: str | Unset = UNSET
    ) -> ApiResponse[None]:
        """Claim available rewards; include response metadata."""
        return cast(
            ApiResponse[None],
            await self._client._call_with_response(
                _rewards_claim_create.asyncio_detailed, body=body, accept_language=accept_language
            ),
        )

    async def list(
        self,
        *,
        level: RewardsListLevel | Unset = UNSET,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        user_email: str | Unset = UNSET,
        user_id: UUID | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedRewardList:
        """List account rewards"""
        return cast(
            PaginatedRewardList,
            await self._client._call(
                _rewards_list.asyncio_detailed,
                level=level,
                limit=limit,
                offset=offset,
                ordering=ordering,
                user_email=user_email,
                user_id=user_id,
                accept_language=accept_language,
            ),
        )

    async def list_with_response(
        self,
        *,
        level: RewardsListLevel | Unset = UNSET,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        user_email: str | Unset = UNSET,
        user_id: UUID | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> ApiResponse[PaginatedRewardList]:
        """List account rewards; include response metadata."""
        return cast(
            ApiResponse[PaginatedRewardList],
            await self._client._call_with_response(
                _rewards_list.asyncio_detailed,
                level=level,
                limit=limit,
                offset=offset,
                ordering=ordering,
                user_email=user_email,
                user_id=user_id,
                accept_language=accept_language,
            ),
        )
