# Generated by scripts/generate.py; do not edit.
from __future__ import annotations

from typing import Any, cast

from ..files import FileDownload
from .._generated.models.session_delete_response import SessionDeleteResponse
from .._generated.models.session_list_response import SessionListResponse
from .._generated.types import UNSET
from .._generated.types import Unset
from .._generated.api.sessions import sessions_destroy as _sessions_destroy
from .._generated.api.sessions import sessions_list as _sessions_list


class SessionsResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    def delete(self, id: str, *, accept_language: str | Unset = UNSET) -> SessionDeleteResponse:
        """Revoke a proxy session"""
        return cast(
            SessionDeleteResponse,
            self._client._call(
                _sessions_destroy.sync_detailed, id=id, accept_language=accept_language
            ),
        )

    def list(self, *, accept_language: str | Unset = UNSET) -> list[SessionListResponse]:
        """List active proxy sessions"""
        return cast(
            list[SessionListResponse],
            self._client._call(_sessions_list.sync_detailed, accept_language=accept_language),
        )


class AsyncSessionsResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    async def delete(
        self, id: str, *, accept_language: str | Unset = UNSET
    ) -> SessionDeleteResponse:
        """Revoke a proxy session"""
        return cast(
            SessionDeleteResponse,
            await self._client._call(
                _sessions_destroy.asyncio_detailed, id=id, accept_language=accept_language
            ),
        )

    async def list(self, *, accept_language: str | Unset = UNSET) -> list[SessionListResponse]:
        """List active proxy sessions"""
        return cast(
            list[SessionListResponse],
            await self._client._call(
                _sessions_list.asyncio_detailed, accept_language=accept_language
            ),
        )
