# Generated by scripts/generate.py; do not edit.
from __future__ import annotations

from typing import Any, cast

from ..files import FileDownload
from .._generated.models.settings_response import SettingsResponse
from .._generated.types import UNSET
from .._generated.types import Unset
from .._generated.api.settings import settings_retrieve as _settings_retrieve


class SettingsResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    def get(self, *, accept_language: str | Unset = UNSET) -> SettingsResponse:
        """Get account settings"""
        return cast(
            SettingsResponse,
            self._client._call(_settings_retrieve.sync_detailed, accept_language=accept_language),
        )


class AsyncSettingsResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    async def get(self, *, accept_language: str | Unset = UNSET) -> SettingsResponse:
        """Get account settings"""
        return cast(
            SettingsResponse,
            await self._client._call(
                _settings_retrieve.asyncio_detailed, accept_language=accept_language
            ),
        )
