# Generated by scripts/generate.py; do not edit.
from __future__ import annotations

from typing import Any, cast

from ..files import FileDownload
from .._generated.models.telegram_connection_response import TelegramConnectionResponse
from .._generated.models.telegram_link_consume_request import TelegramLinkConsumeRequest
from .._generated.models.telegram_session_request import TelegramSessionRequest
from .._generated.models.telegram_session_response import TelegramSessionResponse
from .._generated.types import UNSET
from .._generated.types import Unset
from .._generated.api.telegram_dashboard_service import (
    integrations_telegram_link_consume_create as _integrations_telegram_link_consume_create,
)
from .._generated.api.telegram_dashboard_service import (
    integrations_telegram_session_create as _integrations_telegram_session_create,
)


class TelegramServiceResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    def consume_link(
        self,
        *,
        body: TelegramLinkConsumeRequest,
        service_secret: str,
        accept_language: str | Unset = UNSET,
    ) -> TelegramConnectionResponse:
        """Consume a Telegram account link"""
        return cast(
            TelegramConnectionResponse,
            self._client._call(
                _integrations_telegram_link_consume_create.sync_detailed,
                body=body,
                x_proxy_request_telegram_secret=service_secret,
                accept_language=accept_language,
            ),
        )

    def create_session(
        self,
        *,
        body: TelegramSessionRequest,
        service_secret: str,
        accept_language: str | Unset = UNSET,
    ) -> TelegramSessionResponse:
        """Create a Telegram API session"""
        return cast(
            TelegramSessionResponse,
            self._client._call(
                _integrations_telegram_session_create.sync_detailed,
                body=body,
                x_proxy_request_telegram_secret=service_secret,
                accept_language=accept_language,
            ),
        )


class AsyncTelegramServiceResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    async def consume_link(
        self,
        *,
        body: TelegramLinkConsumeRequest,
        service_secret: str,
        accept_language: str | Unset = UNSET,
    ) -> TelegramConnectionResponse:
        """Consume a Telegram account link"""
        return cast(
            TelegramConnectionResponse,
            await self._client._call(
                _integrations_telegram_link_consume_create.asyncio_detailed,
                body=body,
                x_proxy_request_telegram_secret=service_secret,
                accept_language=accept_language,
            ),
        )

    async def create_session(
        self,
        *,
        body: TelegramSessionRequest,
        service_secret: str,
        accept_language: str | Unset = UNSET,
    ) -> TelegramSessionResponse:
        """Create a Telegram API session"""
        return cast(
            TelegramSessionResponse,
            await self._client._call(
                _integrations_telegram_session_create.asyncio_detailed,
                body=body,
                x_proxy_request_telegram_secret=service_secret,
                accept_language=accept_language,
            ),
        )
