# Generated by scripts/generate.py; do not edit.
from __future__ import annotations

from typing import Any, cast

from ..files import FileDownload
from .._generated.models.add_data_request import AddDataRequest
from .._generated.models.order import Order
from .._generated.models.paginated_order_list import PaginatedOrderList
from .._generated.models.paginated_user_list import PaginatedUserList
from .._generated.models.patched_user_update_request import PatchedUserUpdateRequest
from .._generated.models.subtract_data_request import SubtractDataRequest
from .._generated.types import UNSET
from uuid import UUID
from .._generated.types import Unset
from .._generated.models.user import User
from .._generated.models.user_create_request import UserCreateRequest
from .._generated.models.user_password_reset_request import UserPasswordResetRequest
from .._generated.api.users import users_data_add_create as _users_data_add_create
from .._generated.api.users import users_create as _users_create
from .._generated.api.users import users_destroy as _users_destroy
from .._generated.api.users import users_retrieve as _users_retrieve
from .._generated.api.users import users_list as _users_list
from .._generated.api.users import users_orders_list as _users_orders_list
from .._generated.api.users import users_password_create as _users_password_create
from .._generated.api.users import users_data_subtract_create as _users_data_subtract_create
from .._generated.api.users import users_partial_update as _users_partial_update


class UsersResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    def add_data(
        self, id: UUID, *, body: AddDataRequest, accept_language: str | Unset = UNSET
    ) -> Order:
        """Add data to a sub-user order"""
        return cast(
            Order,
            self._client._call(
                _users_data_add_create.sync_detailed,
                id=id,
                body=body,
                accept_language=accept_language,
            ),
        )

    def create(self, *, body: UserCreateRequest, accept_language: str | Unset = UNSET) -> User:
        """Create a sub-user"""
        return cast(
            User,
            self._client._call(
                _users_create.sync_detailed, body=body, accept_language=accept_language
            ),
        )

    def delete(self, id: UUID, *, accept_language: str | Unset = UNSET) -> None:
        """Delete a user"""
        self._client._call(_users_destroy.sync_detailed, id=id, accept_language=accept_language)
        return None

    def get(self, id: UUID, *, accept_language: str | Unset = UNSET) -> User:
        """Get a user"""
        return cast(
            User,
            self._client._call(
                _users_retrieve.sync_detailed, id=id, accept_language=accept_language
            ),
        )

    def list(
        self,
        *,
        email: str | Unset = UNSET,
        id: UUID | Unset = UNSET,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        package_id: UUID | Unset = UNSET,
        search: str | Unset = UNSET,
        username: str | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedUserList:
        """List users in the current account"""
        return cast(
            PaginatedUserList,
            self._client._call(
                _users_list.sync_detailed,
                email=email,
                id=id,
                limit=limit,
                offset=offset,
                ordering=ordering,
                package_id=package_id,
                search=search,
                username=username,
                accept_language=accept_language,
            ),
        )

    def list_orders(
        self,
        id_path: UUID,
        *,
        email: str | Unset = UNSET,
        id_query: UUID | Unset = UNSET,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        username: str | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedOrderList:
        """List a sub-user's orders"""
        return cast(
            PaginatedOrderList,
            self._client._call(
                _users_orders_list.sync_detailed,
                id_path=id_path,
                email=email,
                id_query=id_query,
                limit=limit,
                offset=offset,
                ordering=ordering,
                username=username,
                accept_language=accept_language,
            ),
        )

    def reset_password(
        self,
        id: UUID,
        *,
        body: UserPasswordResetRequest | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> User:
        """Rotate a sub-user proxy password"""
        return cast(
            User,
            self._client._call(
                _users_password_create.sync_detailed,
                id=id,
                body=body,
                accept_language=accept_language,
            ),
        )

    def subtract_data(
        self, id: UUID, *, body: SubtractDataRequest, accept_language: str | Unset = UNSET
    ) -> Order:
        """Subtract data from a sub-user order"""
        return cast(
            Order,
            self._client._call(
                _users_data_subtract_create.sync_detailed,
                id=id,
                body=body,
                accept_language=accept_language,
            ),
        )

    def update(
        self,
        id: UUID,
        *,
        body: PatchedUserUpdateRequest | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> User:
        """Update a user"""
        return cast(
            User,
            self._client._call(
                _users_partial_update.sync_detailed,
                id=id,
                body=body,
                accept_language=accept_language,
            ),
        )


class AsyncUsersResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    async def add_data(
        self, id: UUID, *, body: AddDataRequest, accept_language: str | Unset = UNSET
    ) -> Order:
        """Add data to a sub-user order"""
        return cast(
            Order,
            await self._client._call(
                _users_data_add_create.asyncio_detailed,
                id=id,
                body=body,
                accept_language=accept_language,
            ),
        )

    async def create(
        self, *, body: UserCreateRequest, accept_language: str | Unset = UNSET
    ) -> User:
        """Create a sub-user"""
        return cast(
            User,
            await self._client._call(
                _users_create.asyncio_detailed, body=body, accept_language=accept_language
            ),
        )

    async def delete(self, id: UUID, *, accept_language: str | Unset = UNSET) -> None:
        """Delete a user"""
        await self._client._call(
            _users_destroy.asyncio_detailed, id=id, accept_language=accept_language
        )
        return None

    async def get(self, id: UUID, *, accept_language: str | Unset = UNSET) -> User:
        """Get a user"""
        return cast(
            User,
            await self._client._call(
                _users_retrieve.asyncio_detailed, id=id, accept_language=accept_language
            ),
        )

    async def list(
        self,
        *,
        email: str | Unset = UNSET,
        id: UUID | Unset = UNSET,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        package_id: UUID | Unset = UNSET,
        search: str | Unset = UNSET,
        username: str | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedUserList:
        """List users in the current account"""
        return cast(
            PaginatedUserList,
            await self._client._call(
                _users_list.asyncio_detailed,
                email=email,
                id=id,
                limit=limit,
                offset=offset,
                ordering=ordering,
                package_id=package_id,
                search=search,
                username=username,
                accept_language=accept_language,
            ),
        )

    async def list_orders(
        self,
        id_path: UUID,
        *,
        email: str | Unset = UNSET,
        id_query: UUID | Unset = UNSET,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        ordering: str | Unset = UNSET,
        username: str | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedOrderList:
        """List a sub-user's orders"""
        return cast(
            PaginatedOrderList,
            await self._client._call(
                _users_orders_list.asyncio_detailed,
                id_path=id_path,
                email=email,
                id_query=id_query,
                limit=limit,
                offset=offset,
                ordering=ordering,
                username=username,
                accept_language=accept_language,
            ),
        )

    async def reset_password(
        self,
        id: UUID,
        *,
        body: UserPasswordResetRequest | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> User:
        """Rotate a sub-user proxy password"""
        return cast(
            User,
            await self._client._call(
                _users_password_create.asyncio_detailed,
                id=id,
                body=body,
                accept_language=accept_language,
            ),
        )

    async def subtract_data(
        self, id: UUID, *, body: SubtractDataRequest, accept_language: str | Unset = UNSET
    ) -> Order:
        """Subtract data from a sub-user order"""
        return cast(
            Order,
            await self._client._call(
                _users_data_subtract_create.asyncio_detailed,
                id=id,
                body=body,
                accept_language=accept_language,
            ),
        )

    async def update(
        self,
        id: UUID,
        *,
        body: PatchedUserUpdateRequest | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> User:
        """Update a user"""
        return cast(
            User,
            await self._client._call(
                _users_partial_update.asyncio_detailed,
                id=id,
                body=body,
                accept_language=accept_language,
            ),
        )
