# Generated by scripts/generate.py; do not edit.
from __future__ import annotations

from typing import Any, cast

from ..files import FileDownload
from .._generated.models.paginated_webhook_list import PaginatedWebhookList
from .._generated.types import UNSET
from .._generated.types import Unset
from .._generated.models.webhook_create_request import WebhookCreateRequest
from .._generated.models.webhook_created import WebhookCreated
from .._generated.models.webhook_list import WebhookList
from .._generated.api.webhooks import webhooks_create as _webhooks_create
from .._generated.api.webhooks import webhooks_destroy as _webhooks_destroy
from .._generated.api.webhooks import webhooks_retrieve as _webhooks_retrieve
from .._generated.api.webhooks import webhooks_list as _webhooks_list


class WebhooksResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    def create(
        self, *, body: WebhookCreateRequest, accept_language: str | Unset = UNSET
    ) -> WebhookCreated:
        """Create a customer webhook"""
        return cast(
            WebhookCreated,
            self._client._call(
                _webhooks_create.sync_detailed, body=body, accept_language=accept_language
            ),
        )

    def delete(self, id: str, *, accept_language: str | Unset = UNSET) -> None:
        """Delete a customer webhook"""
        self._client._call(_webhooks_destroy.sync_detailed, id=id, accept_language=accept_language)
        return None

    def get(self, id: str, *, accept_language: str | Unset = UNSET) -> WebhookList:
        """Get a customer webhook"""
        return cast(
            WebhookList,
            self._client._call(
                _webhooks_retrieve.sync_detailed, id=id, accept_language=accept_language
            ),
        )

    def list(
        self,
        *,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedWebhookList:
        """List customer webhooks"""
        return cast(
            PaginatedWebhookList,
            self._client._call(
                _webhooks_list.sync_detailed,
                limit=limit,
                offset=offset,
                accept_language=accept_language,
            ),
        )


class AsyncWebhooksResource:
    def __init__(self, client: Any) -> None:
        self._client = client

    async def create(
        self, *, body: WebhookCreateRequest, accept_language: str | Unset = UNSET
    ) -> WebhookCreated:
        """Create a customer webhook"""
        return cast(
            WebhookCreated,
            await self._client._call(
                _webhooks_create.asyncio_detailed, body=body, accept_language=accept_language
            ),
        )

    async def delete(self, id: str, *, accept_language: str | Unset = UNSET) -> None:
        """Delete a customer webhook"""
        await self._client._call(
            _webhooks_destroy.asyncio_detailed, id=id, accept_language=accept_language
        )
        return None

    async def get(self, id: str, *, accept_language: str | Unset = UNSET) -> WebhookList:
        """Get a customer webhook"""
        return cast(
            WebhookList,
            await self._client._call(
                _webhooks_retrieve.asyncio_detailed, id=id, accept_language=accept_language
            ),
        )

    async def list(
        self,
        *,
        limit: int | Unset = UNSET,
        offset: int | Unset = UNSET,
        accept_language: str | Unset = UNSET,
    ) -> PaginatedWebhookList:
        """List customer webhooks"""
        return cast(
            PaginatedWebhookList,
            await self._client._call(
                _webhooks_list.asyncio_detailed,
                limit=limit,
                offset=offset,
                accept_language=accept_language,
            ),
        )
